version: '3'

services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'

  # For server I need to:
  # 1) Specify a build
  # 2) Specify volumes
  # 3) Specify env variables
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # Inside a container, don't try to override this folder (telling container to leave this folder as it is)
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app